import { NextResponse } from 'next/server';

// Add dynamic route configuration
export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function POST(request: Request) {
  try {
    const formData = await request.formData();
    const file = formData.get('file') as File | null;

    if (!file) {
      return NextResponse.json(
        { success: false, error: 'No file uploaded' },
        { status: 400 }
      );
    }

    // In a real implementation, this would:
    // 1. Parse the uploaded blood report using OCR
    // 2. Process the report with AI analysis
    // 3. Return detailed interpretation

    // Simulating processing delay
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Mock response
    return NextResponse.json({
      success: true,
      analysis: {
        summary: 'Your blood report shows values within normal ranges with a few minor exceptions.',
        abnormalValues: [
          {
            test: 'LDL Cholesterol',
            value: '135 mg/dL',
            normalRange: 'Less than 100 mg/dL',
            interpretation: 'Slightly elevated, consider dietary changes',
            severity: 'mild'
          },
          {
            test: 'Vitamin D',
            value: '22 ng/mL',
            normalRange: '30-100 ng/mL',
            interpretation: 'Below normal range, supplementation recommended',
            severity: 'moderate'
          }
        ],
        normalValues: [
          {
            test: 'HDL Cholesterol',
            value: '55 mg/dL',
            normalRange: '40-60 mg/dL',
            interpretation: 'Within healthy range'
          },
          {
            test: 'Hemoglobin',
            value: '14.2 g/dL',
            normalRange: '13.5-17.5 g/dL',
            interpretation: 'Normal'
          }
        ],
        recommendations: [
          'Consider reducing saturated fat intake to lower LDL cholesterol',
          'Start Vitamin D supplementation under medical supervision',
          'Continue maintaining healthy diet and exercise habits',
          'Schedule follow-up in 3 months to recheck values'
        ],
        disclaimer: 'This analysis is generated by AI and should be reviewed by a healthcare professional. It does not constitute medical advice.'
      }
    });
  } catch (error) {
    console.error('Error analyzing blood report:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to analyze blood report'
      },
      { status: 500 }
    );
  }
}